"use client";

import { useCallback, useEffect, useState } from "react";
import { calculate, emptyPayrollInput, money, sumTotals, type PayrollDocument, type PayrollInput } from "../lib/payroll-calculation";
import { previousMonth } from "../lib/payroll-attendance";
import "./payroll.css";

type Employee = { id: string; name: string; email: string; salary: number; position_title: string };
type RunSummary = { id: string; period: string; label: string; status: string; net: number; employee_count: number; revision: number };
type Slip = { id: string; employee_name?: string; recipient_email?: string; delivery_status?: string; last_error?: string; provider_id?: string; period?: string; label?: string; status?: string; net: number };
type Run = RunSummary & { document: PayrollDocument; approved_by: string | null; approved_at: string | null; payment_reference: string | null };
type Event = { revision: number; action: string; actor_name: string; reason: string; created_at: string };
type Award = { id: string; employee_name: string; kind: string; label: string; amount: number; start_month: string; end_month: string };
type Source = { id: string; employee_id: string; label: string };
type Data = { mode: "admin" | "employee"; owner?: boolean; employees?: Employee[]; runs?: RunSummary[]; slips?: Slip[]; awards?: Award[]; sources?: { skills: Source[]; quests: Source[] }; mail?: { ready: boolean; sender?: string; missing?: string[] } };
type Draft = { label: string; period: string; startDate: string; endDate: string; payDate: string; policyNote: string; entries: PayrollInput[] };
const states: Record<string, string> = { draft: "ร่าง • ตรวจยอด", approved: "อนุมัติแล้ว", paid: "บันทึกจ่ายแล้ว", void: "ยกเลิกร่าง" };
const deliveryStates: Record<string, string> = { pending: "รอส่ง", sending: "กำลังส่ง", accepted: "บริการอีเมลรับแล้ว", failed: "รอลองใหม่", review: "ต้องตรวจสอบ" };
function blankDraft(): Draft {
  const now = new Date(), year = now.getFullYear(), month = String(now.getMonth() + 1).padStart(2, "0"), period = `${year}-${month}`;
  const endDate = `${period}-${new Date(year, now.getMonth() + 1, 0).getDate()}`;
  return { label: `เงินเดือน ${period}`, period, startDate: `${period}-01`, endDate, payDate: endDate, policyNote: "", entries: [] };
}
async function request<T>(url: string, body?: object): Promise<T> {
  const response = await fetch(url, { cache: "no-store", ...(body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {}) });
  const result = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(result.error || "เชื่อมต่อไม่ได้ กรุณาโหลดข้อมูลใหม่");
  return result;
}
export default function PayrollCenter() {
  const [data, setData] = useState<Data | null>(null), [run, setRun] = useState<Run | null>(null), [slips, setSlips] = useState<Slip[]>([]), [events, setEvents] = useState<Event[]>([]);
  const [draft, setDraft] = useState<Draft>(blankDraft), [editing, setEditing] = useState(false), [dirty, setDirty] = useState(false), [selected, setSelected] = useState(0);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [message, setMessage] = useState(""), [confirmed, setConfirmed] = useState(false), [overlapConfirmed, setOverlapConfirmed] = useState(false), [guide, setGuide] = useState(false);
  const [award, setAward] = useState({ employeeId: "", kind: "skill", sourceId: "", amount: "500", startMonth: blankDraft().period, endMonth: blankDraft().period });
  const refresh = useCallback(async () => setData(await request<Data>("/api/payroll")), []);
  useEffect(() => { let active = true; request<Data>("/api/payroll").then(result => { if (active) setData(result); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
  useEffect(() => { if (!dirty) return; const prevent = (event: BeforeUnloadEvent) => { event.preventDefault(); }; window.addEventListener("beforeunload", prevent); return () => window.removeEventListener("beforeunload", prevent); }, [dirty]);
  const loadRun = async (id: string) => {
    const result = await request<{ run: Run; slips: Slip[]; events: Event[] }>(`/api/payroll?run=${encodeURIComponent(id)}`);
    setRun(result.run); setDraft(result.run.document); setSlips(result.slips); setEvents(result.events); setEditing(true); setDirty(false); setSelected(0); setConfirmed(false); setOverlapConfirmed(false);
  };
  const choose = async (id: string) => {
    if (dirty && !window.confirm("มีข้อมูลที่ยังไม่ได้บันทึก ต้องการออกจากร่างนี้หรือไม่?")) return;
    setBusy(true); setError(""); setMessage(""); try { await loadRun(id); } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  const update = (next: Partial<Draft>) => { setDraft(d => ({ ...d, ...next })); setDirty(true); setConfirmed(false); };
  const updateEntry = (next: Partial<PayrollInput>) => { update({ entries: draft.entries.map((entry, i) => i === selected ? { ...entry, ...next } : entry) }); };
  const writable = !run || run.status === "draft";
  let totals: ReturnType<typeof sumTotals> | null = null, calculationError = "";
  try { totals = sumTotals(draft.entries.map(entry => ({ totals: calculate(entry) }))); } catch (e) { calculationError = (e as Error).message; }
  const perform = async (action: string, extra: object = {}) => {
    setBusy(true); setError(""); setMessage("");
    try {
      const editable = action === "save" || action === "create" ? { ...draft, entries: draft.entries.map(e => Object.fromEntries(Object.entries(e).filter(([key]) => !["employeeName", "positionTitle", "totals", "skillBonus", "questBonus", "attendanceBonus", "attendanceReview", "awardIds"].includes(key)))) } : {};
      const result = await request<{ id: string }>("/api/payroll", { ...editable, action, id: run?.id, expectedRevision: run?.revision, confirmed, overlapConfirmed, ...extra });
      await refresh(); await loadRun(result.id);
      setMessage(action === "approve" ? "อนุมัติและล็อกสลิปแล้ว ยังไม่มีการโอนเงินหรือส่งอีเมล" : action === "paid" ? "บันทึกหลักฐานการจ่ายแล้ว (ระบบไม่ได้โอนเงิน)" : action === "void" ? "ยกเลิกร่างแล้ว ประวัติยังอยู่" : "บันทึกและคำนวณร่างเรียบร้อย");
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  const send = async (slip: Slip) => {
    if (!window.confirm(`ส่งลิงก์สลิปให้ ${slip.employee_name} ที่ ${slip.recipient_email} ใช่หรือไม่?`)) return;
    setBusy(true); setError("");
    try { await request("/api/payroll", { action: "send", slipId: slip.id }); if (run) await loadRun(run.id); setMessage("Gmail รับอีเมลแล้ว ไม่ได้ยืนยันว่าเข้ากล่องจดหมาย สามารถตรวจได้ที่โฟลเดอร์ Sent ของบริษัท"); }
    catch (e) { setError((e as Error).message); if (run) await loadRun(run.id).catch(() => {}); } finally { setBusy(false); }
  };
  const addAward = async () => {
    if (!window.confirm("ยืนยันเงินเพิ่มตามช่วงเวลานี้? เมื่อกำหนดแล้วรายการจะถูกเก็บเป็นหลักฐานและแก้ย้อนหลังไม่ได้")) return;
    setBusy(true); setError("");
    try { await request("/api/payroll", { action: "createAward", ...award }); await refresh(); setMessage("กำหนดเงินเพิ่มแล้ว เลือกรับเงินเพิ่มประจำเดือนในวิคที่ต้องการ จากนั้นบันทึกร่างเพื่อคำนวณ"); }
    catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  };
  const entry = draft.entries[selected], activeEmployee = data?.employees?.find(e => e.id === entry?.employeeId);
  const attendanceMonth = previousMonth(draft.period);
  const attendanceLastDay = new Date(Date.UTC(+attendanceMonth.slice(0, 4), +attendanceMonth.slice(5), 0)).getUTCDate();
  const entryTotals = (() => { try { return entry ? calculate(entry) : null; } catch { return null; } })();
  const field = (key: keyof PayrollInput, name: string, hint?: string) => <label className="payroll-field" key={key}><span>{name}</span><input inputMode="decimal" value={String(entry?.[key] ?? "")} disabled={!writable || busy} onChange={event => updateEntry({ [key]: event.target.value })} /><small>{hint || "บาท · ทศนิยมไม่เกิน 2 ตำแหน่ง"}</small></label>;
  return <section className="payroll-center" aria-label="เงินเดือนและค่าคอมมิชชัน">
    <header className="payroll-hero"><div><span className="payroll-eyebrow">PAYROLL & COMMISSION</span><h2>{data?.mode === "employee" ? "สลิปของฉัน" : "เงินเดือนที่ตรวจสอบได้ทุกบาท"}</h2><p>{data?.mode === "employee" ? "เปิดดูสลิปที่อนุมัติแล้วของคุณ พิมพ์หรือบันทึกเป็น PDF ได้" : "เตรียมยอด → ตรวจและอนุมัติ → ออกสลิป → บันทึกการจ่าย"}</p></div><button onClick={() => setGuide(!guide)} aria-expanded={guide}>เรียนรู้การใช้งาน</button></header>
    {error && <div className="payroll-notice error" role="alert">{error}<button disabled={busy} onClick={() => { setError(""); void refresh().catch(e => setError(e.message)); }}>โหลดรายการล่าสุด</button></div>}
    {message && <div className="payroll-notice success" role="status">{message}</div>}
    {guide && <div className="payroll-card payroll-guide"><h3>เริ่มใช้ให้ถูกต้อง</h3><ol><li>HR/Admin สร้างรอบ เลือกพนักงาน และตรวจอีเมลจริงของแต่ละคน</li><li>กำหนดค่าแรงและหน่วยจ่าย เช่น รายวัน 500 × 22 วัน = 11,000 บาท หรือรายเดือน 20,000 × 1 = 20,000 บาท</li><li>OT ใช้อัตราต่อชั่วโมงที่บริษัทอนุมัติ เช่น 2 ชั่วโมง × 150 = 300 บาท ไม่ดึงอัตราตามกฎหมายให้อัตโนมัติ</li><li>คอมมิชชัน: ฐาน 100,000 × 2.50% = 2,500 บาท + คงที่ถ้ามี ระบุเลขเอกสาร/ยอดขายหรือกำไรที่ตรวจแล้ว ห้ามนับเอกสารเดิมซ้ำ</li><li>ตรวจภาษี ประกันสังคม และรายการหักกับผู้รับผิดชอบ บันทึกกติกาให้ชัดเจน ค่า 0 ไม่ได้แปลว่าตรวจแล้ว</li><li>บันทึกร่าง เจ้าของตรวจยอดและอีเมล ติ๊กยืนยันแล้วอนุมัติ สลิปจะล็อกและพนักงานเห็นเฉพาะของตัวเอง</li><li>โอนเงินผ่านช่องทางบริษัทก่อน แล้วจึงกด “บันทึกจ่ายแล้ว” พร้อมเลขอ้างอิง ส่งอีเมลได้เมื่อบริการพร้อม</li></ol><p><strong>ข้อควรระวัง:</strong> เงินเดือนเดิมรวมเงินเพิ่มจากทักษะแล้ว ห้ามบวกซ้ำ · ไม่แปลง Points/KPI เป็นค่าแรงอัตโนมัติ · ไม่หักวันลา/มาสายอัตโนมัติ · สลิปอนุมัติแก้ย้อนหลังไม่ได้ ให้ HR ตรวจและจัดทำรอบเพิ่มเติมพร้อมหลักฐาน หากต้องลดหรือยกเลิกยอดเดิมให้ประสานบัญชีก่อน (ระบบยังไม่ออกยอดติดลบ)</p><p>หัวหน้าไม่มีสิทธิ์อ่านเงินเดือนทีม พนักงานที่ลาออกไม่สามารถเข้าสู่ระบบเดิมได้ ให้ HR ส่งมอบเอกสารตามขั้นตอนบริษัท</p></div>}
    {!data && !error && <div className="payroll-card" role="status">กำลังโหลดข้อมูลเงินเดือน…</div>}
    {data?.mode === "employee" && <div className="payroll-card"><h3>สลิปที่อนุมัติแล้ว</h3>{!data.slips?.length ? <p>ยังไม่มีสลิปที่อนุมัติสำหรับบัญชีนี้</p> : <div className="payroll-slip-grid">{data.slips.map(s => <article className="payroll-slip" key={s.id}><span className="payroll-badge">{s.period}</span><h3>{s.label}</h3><strong>{money(s.net)} บาท</strong><p>{states[s.status ?? "approved"]}</p><a href={`/api/payroll?slip=${encodeURIComponent(s.id)}&print=1`} target="_blank" rel="noreferrer">เปิดสลิป / พิมพ์ PDF ↗</a></article>)}</div>}</div>}
    {data?.mode === "admin" && <>
      <div className="payroll-stats"><div><span>รอบล่าสุด</span><strong>{data.runs?.length ?? 0}</strong><small>แสดงล่าสุดไม่เกิน 120 รอบ</small></div><div><span>รอตรวจอนุมัติ</span><strong>{data.runs?.filter(r => r.status === "draft").length ?? 0}</strong><small>อนุมัติโดยเจ้าของระบบเท่านั้น</small></div><div><span>อีเมลสลิป</span><strong className="payroll-status-text">{data.mail?.ready ? "ตั้งค่าแล้ว" : "ยังไม่เชื่อม"}</strong><small>ลิงก์ส่วนตัว · ต้องเข้าสู่ระบบ</small></div></div>
      {!data.mail?.ready && <div className="payroll-notice">ออกสลิปและพิมพ์ PDF ได้ แต่ยังส่งอีเมลจริงไม่ได้ {data.owner && <>ผู้ส่งบริษัท: maechalao2333@gmail.com · ต้องเชื่อมสิทธิ์ Gmail: <code>{data.mail?.missing?.join(", ")}</code> ไม่ต้องส่งรหัสผ่านหรือ token ในแชต</>}</div>}
      <details className="payroll-card"><summary>เงินเพิ่มสกิลชั่วคราว / โบนัสเควส ({data.awards?.length ?? 0})</summary><p className="payroll-help">เช่น สกิลใหม่ +500 บาท/เดือน 3 เดือน ให้ตั้งเดือนเริ่มและสิ้นสุดครบ 3 เดือน ระบบหยุดคิดเมื่อพ้นช่วง และไม่จ่ายซ้ำหลายวิค · โบนัสเควสจ่ายครั้งเดียวตามยอดที่เจ้าของกำหนด ไม่แปลง Points เป็นเงิน</p>
        {data.owner && <><div className="payroll-form-grid"><label className="payroll-field"><span>พนักงาน</span><select value={award.employeeId} onChange={e => setAward({ ...award, employeeId: e.target.value, sourceId: "" })}><option value="">เลือกพนักงาน…</option>{data.employees?.map(e => <option value={e.id} key={e.id}>{e.name}</option>)}</select></label><label className="payroll-field"><span>ประเภทเงินเพิ่ม</span><select value={award.kind} onChange={e => setAward({ ...award, kind: e.target.value, sourceId: "" })}><option value="skill">เงินเพิ่มสกิลรายเดือน มีวันหมดอายุ</option><option value="quest">โบนัสเควสครั้งเดียว</option></select></label><label className="payroll-field"><span>สกิล/เควสที่ยืนยันสำเร็จแล้ว</span><select value={award.sourceId} onChange={e => setAward({ ...award, sourceId: e.target.value })}><option value="">เลือกรายการจริง…</option>{(award.kind === "skill" ? data.sources?.skills : data.sources?.quests)?.filter(s => s.employee_id === award.employeeId).map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></label><label className="payroll-field"><span>เงินเพิ่ม (บาท/เดือน)</span><input inputMode="decimal" value={award.amount} onChange={e => setAward({ ...award, amount: e.target.value })} /></label><label className="payroll-field"><span>เริ่มเดือน</span><input type="month" value={award.startMonth} onChange={e => setAward({ ...award, startMonth: e.target.value, ...(award.kind === "quest" ? { endMonth: e.target.value } : {}) })} /></label><label className="payroll-field"><span>สิ้นสุดเดือน (รวมเดือนนี้)</span><input type="month" value={award.endMonth} disabled={award.kind === "quest"} onChange={e => setAward({ ...award, endMonth: e.target.value })} /></label></div><button className="primary" disabled={busy || !award.sourceId} onClick={() => void addAward()}>ยืนยันเงินเพิ่มตามช่วงเวลา</button></>}
        <div className="payroll-slip-grid" style={{ marginTop: 16 }}>{data.awards?.map(a => <article className="payroll-slip" key={a.id}><h4>{a.employee_name}</h4><p>{a.kind === "skill" ? "สกิล" : "เควส"}: {a.label}</p><strong>{money(a.amount)} บาท</strong><small>{a.start_month} ถึง {a.end_month}</small></article>)}</div>
      </details>
      <div className="payroll-workspace"><aside className="payroll-card payroll-run-list"><div className="payroll-section-title"><h3>รอบจ่าย</h3><button className="primary" disabled={busy} onClick={() => { if (dirty && !window.confirm("ออกจากร่างที่ยังไม่บันทึก?")) return; setRun(null); setDraft(blankDraft()); setEditing(true); setDirty(false); setSelected(0); setSlips([]); setEvents([]); setError(""); setMessage(""); }}>+ สร้างรอบ</button></div>{!data.runs?.length && <p>ยังไม่มีรอบจ่าย เริ่มสร้างร่างได้เลย</p>}{data.runs?.map(r => <button className={`payroll-run ${run?.id === r.id ? "selected" : ""}`} key={r.id} disabled={busy} onClick={() => void choose(r.id)}><span>{r.label}</span><small>{r.period} · {r.employee_count} คน</small><strong>{money(r.net)} บาท</strong><span className={`payroll-badge ${r.status}`}>{states[r.status]}</span></button>)}</aside>
        <div className="payroll-main">{!editing ? <div className="payroll-card payroll-empty"><span>฿</span><h3>เริ่มจากรอบจ่ายหนึ่งรอบ</h3><p>เลือกเดือน เพิ่มพนักงาน แล้วตรวจยอดก่อนออกสลิป ข้อมูลเดิมในระบบจะไม่ถูกลบ</p></div> : <>
          <div className="payroll-card"><div className="payroll-section-title"><h3>{run ? draft.label : "รอบจ่ายใหม่"}</h3><span className={`payroll-badge ${run?.status ?? "draft"}`}>{dirty ? "มีการแก้ไขยังไม่บันทึก" : states[run?.status ?? "draft"]}</span></div>
            <div className="payroll-form-grid"><label className="payroll-field"><span>ชื่อรอบจ่าย</span><input value={draft.label} maxLength={120} disabled={!writable || busy} onChange={e => update({ label: e.target.value })} /></label><label className="payroll-field"><span>เดือนอ้างอิง</span><input type="month" value={draft.period} disabled={!!run || busy} onChange={e => update({ period: e.target.value })} /></label>{([ ["startDate", "เริ่มคำนวณ"], ["endDate", "สิ้นสุดคำนวณ"], ["payDate", "กำหนดจ่าย"] ] as const).map(([key, name]) => <label className="payroll-field" key={key}><span>{name}</span><input type="date" value={draft[key]} disabled={!writable || busy} onChange={e => update({ [key]: e.target.value })} /></label>)}</div>
            <label className="payroll-field"><span>กติกาค่าแรง/คอมมิชชันและสิ่งที่ตรวจแล้ว <em>ต้องกรอก</em></span><textarea value={draft.policyNote} disabled={!writable || busy} maxLength={2000} rows={3} placeholder="เช่น รายเดือนเต็มเดือน / คอม 2% จากยอดขายชำระแล้ว หักคืนสินค้า / ภาษีและประกันสังคมตรวจโดยฝ่ายบัญชี…" onChange={e => update({ policyNote: e.target.value })} /></label>
          </div>
          <div className="payroll-card"><h3>พนักงานในรอบนี้ ({draft.entries.length}/80)</h3>{writable && <label className="payroll-field"><span>เพิ่มพนักงาน</span><select value="" disabled={busy || draft.entries.length >= 80} onChange={e => { const employee = data.employees?.find(x => x.id === e.target.value); if (!employee) return; const salary = Number.isFinite(employee.salary) && employee.salary >= 0 && employee.salary < 100000000 ? employee.salary.toFixed(2) : "0"; update({ entries: [...draft.entries, emptyPayrollInput(employee.id, employee.email, salary)] }); setSelected(draft.entries.length); }}><option value="">เลือกพนักงานที่ยังทำงานอยู่…</option>{data.employees?.filter(e => !draft.entries.some(x => x.employeeId === e.id)).map(e => <option value={e.id} key={e.id}>{e.name} · {e.position_title || e.id}</option>)}</select></label>}
            <div className="payroll-employee-tabs">{draft.entries.map((e, i) => <button key={e.employeeId} className={selected === i ? "selected" : ""} onClick={() => setSelected(i)}>{data.employees?.find(x => x.id === e.employeeId)?.name || (e as PayrollDocument["entries"][number]).employeeName || e.employeeId}</button>)}</div>
            {entry ? <><div className="payroll-section-title"><h3>{(entry as PayrollDocument["entries"][number]).employeeName || activeEmployee?.name}</h3>{writable && <button className="danger" disabled={busy} onClick={() => { update({ entries: draft.entries.filter((_, i) => i !== selected) }); setSelected(0); }}>นำออกจากร่าง</button>}</div>
              <p className="payroll-help">ค่าแรงตั้งต้นมาจากแผน HR และรวมเงินเพิ่มจากทักษะแล้ว ต้องตรวจอีกครั้งก่อนอนุมัติ</p>
              <label className="payroll-field"><span>อีเมลผู้รับสลิป — ตรวจว่าเป็นเจ้าของข้อมูลจริง</span><input type="email" value={entry.recipientEmail} disabled={!writable || busy} onChange={e => updateEntry({ recipientEmail: e.target.value })} /></label>
              <fieldset><legend>01 · ค่าแรงและ OT</legend><div className="payroll-form-grid"><label className="payroll-field"><span>รูปแบบค่าแรง</span><select value={entry.wageType} disabled={!writable || busy} onChange={e => updateEntry({ wageType: e.target.value as PayrollInput["wageType"], units: e.target.value === "monthly" ? "1" : "0" })}><option value="monthly">รายเดือน (บรรจุแล้ว)</option><option value="daily">รายวัน</option><option value="hourly">รายชั่วโมง</option></select></label>{field("rate", entry.wageType === "monthly" ? "เงินเดือนเต็มเดือน" : "อัตราค่าแรงต่อหน่วย")}{entry.wageType === "monthly" ? <><label className="payroll-field"><span>แบ่งจ่ายกี่วิคในเดือนนี้</span><select value={entry.installments} disabled={!writable || busy} onChange={e => updateEntry({ installments: e.target.value, installment: "1" })}>{[1,2,3,4,5].map(n => <option key={n} value={n}>{n} วิค{n === 1 ? " (เต็มเดือน)" : ""}</option>)}</select><small>เลือกตามรอบจ่ายจริงของบริษัท</small></label><label className="payroll-field"><span>รอบนี้จ่ายวิคที่</span><select value={entry.installment} disabled={!writable || busy} onChange={e => updateEntry({ installment: e.target.value })}>{Array.from({ length: +entry.installments }, (_, i) => i + 1).map(n => <option key={n} value={n}>วิค {n}</option>)}</select><small>เศษสตางค์ปรับในวิคสุดท้าย ไม่จ่ายวิคเดิมซ้ำ</small></label></> : field("units", "หน่วยที่จ่ายจริง", entry.wageType === "daily" ? "จำนวนวันที่ได้รับค่าแรง รวมวันหยุดจ่ายที่อนุมัติแล้ว" : "จำนวนชั่วโมง 0–744")}{field("otHours", "ชั่วโมง OT", "ชั่วโมงทศนิยม เช่น 1.50 = 1 ชม. 30 นาที")}{field("otRate", "อัตรา OT / ชั่วโมง")}</div><p className="payroll-help">รายเดือนรวมวันหยุดได้รับค่าแรง 4 วันแล้ว ไม่หักวันหยุดและไม่บวกเงินวันหยุดซ้ำ รายวันให้ตรวจจำนวนวันได้รับค่าแรงจริงก่อนกรอก</p></fieldset>
              <fieldset><legend>เงินเพิ่มประจำเดือน — เลือกจ่ายในวิคเดียว</legend><label className="payroll-check"><input type="checkbox" checked={entry.includeMonthlyExtras} disabled={!writable || busy} onChange={e => updateEntry({ includeMonthlyExtras: e.target.checked })} /> รับเงินเพิ่มสกิล โบนัสเควส และตรวจเบี้ยขยันในวิคนี้</label>{entry.includeMonthlyExtras && <><p className="payroll-help">เลือกวันหยุดจริง 4 วันของเดือน {attendanceMonth} เพื่อแยกวันหยุดออกจากวันที่ต้องลงเวลา</p><div className="payroll-form-grid">{[0,1,2,3].map(i => <label className="payroll-field" key={i}><span>วันหยุดที่ {i + 1}</span><input type="date" min={`${attendanceMonth}-01`} max={`${attendanceMonth}-${attendanceLastDay}`} value={entry.restDays.split(",")[i]?.trim() ?? ""} disabled={!writable || busy} onChange={e => { const dates = Array.from({ length: 4 }, (_, n) => entry.restDays.split(",")[n]?.trim() ?? ""); dates[i] = e.target.value; updateEntry({ restDays: dates.join(",") }); }} /></label>)}</div><p className="payroll-help">ต้องมีเวลาเข้างานครบวันทำงาน และไม่มีขาด/ลา/สายตลอดเดือนก่อน ข้อมูลไม่ครบจะไม่ผ่านอัตโนมัติ กด “บันทึกและคำนวณร่าง” เพื่อดึงเงินเพิ่มและตรวจเบี้ยขยันล่าสุด</p><div className="payroll-totals"><div><span>เงินสกิลเดือนนี้</span><strong>{entry.skillBonus} บาท</strong></div><div><span>โบนัสเควส</span><strong>{entry.questBonus} บาท</strong></div><div><span>เบี้ยขยัน</span><strong>{entry.attendanceBonus} บาท</strong></div></div><p className="payroll-help">{(() => { try { return JSON.parse(entry.attendanceReview).message; } catch { return entry.attendanceReview; } })()}</p></>}</fieldset>
              <fieldset><legend>02 · ค่าคอมมิชชันและรายได้เพิ่ม</legend><div className="payroll-form-grid">{field("commissionBase", "ยอดขาย/กำไรฐานคำนวณ")}{field("commissionPercent", "เปอร์เซ็นต์คอมมิชชัน", "0–100% เช่น 2.50")}{field("commissionFixed", "คอมมิชชันคงที่เพิ่มเติม")}{field("allowance", "เงินเพิ่มอื่น (ไม่ซ้ำเงินเดือน)")}{field("bonus", "โบนัส")}</div><label className="payroll-field"><span>หลักฐาน/เลขอ้างอิงคอมมิชชัน</span><input value={entry.commissionReference} maxLength={200} disabled={!writable || busy} onChange={e => updateEntry({ commissionReference: e.target.value })} placeholder="เช่น ยอดขายชำระแล้ว SEP-001–025 หักคืนสินค้า ตรวจโดย…" /></label></fieldset>
              <fieldset><legend>03 · รายการหักที่ตรวจสอบแล้ว</legend><p className="payroll-help">ระบบไม่คำนวณภาษีหรือประกันสังคมตามกฎหมายให้อัตโนมัติ ต้องกรอกยอดที่ฝ่ายบัญชีตรวจแล้ว</p><div className="payroll-form-grid">{field("tax", "ภาษีหัก ณ ที่จ่าย")}{field("socialSecurity", "ประกันสังคม")}{field("otherDeduction", "รายการหักอื่น")}</div><label className="payroll-field"><span>เหตุผลรายการหักอื่นและเอกสารยินยอม</span><input value={entry.deductionNote} maxLength={500} disabled={!writable || busy} onChange={e => updateEntry({ deductionNote: e.target.value })} /></label></fieldset>
              <label className="payroll-field"><span>หมายเหตุเฉพาะคน (แสดงในสลิป)</span><textarea value={entry.note} maxLength={1000} disabled={!writable || busy} onChange={e => updateEntry({ note: e.target.value })} /></label>
              <div className="payroll-person-total"><span>สุทธิคนนี้</span><strong>{entryTotals ? money(entryTotals.net) : "ตรวจข้อมูล"} {entryTotals && "บาท"}</strong></div>
            </> : <p className="payroll-help">ยังไม่มีพนักงานในรอบนี้</p>}
          </div>
          <div className="payroll-card payroll-review"><h3>ตรวจยอดรวมก่อนบันทึก</h3>{calculationError && <p role="alert" className="payroll-error-text">{calculationError}</p>}<div className="payroll-totals"><div><span>รายรับรวม</span><strong>{totals ? money(totals.gross) : "—"}</strong></div><div><span>รายการหัก</span><strong>{totals ? money(totals.deductions) : "—"}</strong></div><div><span>สุทธิ {draft.entries.length} คน</span><strong>{totals ? money(totals.net) : "—"} บาท</strong></div></div>
            {writable && <><p className="payroll-help">รายการตัวเลขเริ่มต้นเป็น 0 ต้องตรวจทุกช่อง ไม่ได้หมายความว่าภาษี/รายการหักได้รับการยืนยันแล้ว</p><div className="payroll-actions"><button className="primary" disabled={busy || !draft.entries.length || !!calculationError} onClick={() => void perform(run ? "save" : "create")}>{busy ? "กำลังทำรายการ…" : "บันทึกและคำนวณร่าง"}</button>{run && <button disabled={busy} onClick={() => void choose(run.id)}>โหลดร่างที่บันทึกไว้</button>}</div>{data.owner && run && <div className="payroll-approval"><label><input type="checkbox" checked={confirmed} disabled={busy || dirty} onChange={e => setConfirmed(e.target.checked)} /> ตรวจค่าแรง OT คอมมิชชัน ภาษี รายการหัก และอีเมลครบแล้ว ยอมรับว่าสลิปจะล็อกหลังอนุมัติ</label><label><input type="checkbox" checked={overlapConfirmed} disabled={busy || dirty} onChange={e => setOverlapConfirmed(e.target.checked)} /> หากเดือนนี้มีสลิปอยู่แล้ว ยืนยันว่ารอบนี้เป็นรอบเพิ่มเติมที่ตั้งใจ ไม่ใช่จ่ายซ้ำ</label><div className="payroll-actions"><button className="primary" disabled={busy || dirty || !confirmed} onClick={() => { if (window.confirm(`อนุมัติ ${draft.entries.length} คน ยอดสุทธิ ${totals ? money(totals.net) : "—"} บาท? สลิปจะไม่สามารถแก้ย้อนหลัง`)) void perform("approve"); }}>อนุมัติและออกสลิป</button><button className="danger" disabled={busy} onClick={() => { const reason = window.prompt("เหตุผลที่ยกเลิกร่าง (ข้อมูลและประวัติจะยังอยู่)"); if (reason) void perform("void", { reason }); }}>ยกเลิกร่าง</button></div>{dirty && <small>บันทึกร่างล่าสุดก่อนอนุมัติ</small>}</div>}</>}
            {!writable && <p>อนุมัติโดย {run?.approved_by || "—"} {run?.payment_reference && <>· หลักฐานการจ่าย: {run.payment_reference}</>}</p>}
            {data.owner && run?.status === "approved" && <button className="primary" disabled={busy} onClick={() => { const reason = window.prompt("โอนเงินจริงแล้วเท่านั้น: ระบุวันที่โอนและเลขอ้างอิง/หลักฐานการจ่าย (ปุ่มนี้ไม่ได้โอนเงิน)"); if (reason) void perform("paid", { reason }); }}>บันทึกจ่ายแล้ว (หลังโอนจริง)</button>}
          </div>
          {!!slips.length && <div className="payroll-card"><h3>สลิปและการส่งอีเมล</h3><p className="payroll-help">อีเมลส่งลิงก์ส่วนตัว ไม่ใส่ยอดเงินในอีเมล · “บริการอีเมลรับแล้ว” ไม่ใช่การยืนยันเข้ากล่องจดหมาย</p><div className="payroll-slip-grid">{slips.map(s => <article className="payroll-slip" key={s.id}><h4>{s.employee_name}</h4><strong>{money(s.net)} บาท</strong><p>{s.recipient_email}</p><span className="payroll-badge">{deliveryStates[s.delivery_status ?? "pending"]}</span>{s.last_error && <p className="payroll-error-text">{s.last_error}</p>}<div className="payroll-actions"><a href={`/api/payroll?slip=${encodeURIComponent(s.id)}&print=1`} target="_blank" rel="noreferrer">เปิด / พิมพ์ PDF ↗</a>{data.owner && <button disabled={busy || !data.mail?.ready || s.delivery_status === "accepted" || s.delivery_status === "review"} onClick={() => void send(s)}>{s.delivery_status === "failed" ? "ลองส่งใหม่" : "ส่งอีเมล"}</button>}</div></article>)}</div></div>}
          {!!events.length && <details className="payroll-card"><summary>ประวัติการเปลี่ยนแปลง ({events.length})</summary><ol className="payroll-history">{events.map(e => <li key={e.revision}><strong>#{e.revision} · {({ create: "สร้างร่าง", save: "แก้ไขร่าง", approve: "อนุมัติ", paid: "บันทึกจ่าย", void: "ยกเลิก" } as Record<string, string>)[e.action]}</strong> — {e.actor_name}<small>{new Date(e.created_at).toLocaleString("th-TH")}{e.reason && ` · ${e.reason}`}</small></li>)}</ol></details>}
        </>}</div>
      </div>
    </>}
  </section>;
}
